# ##############################################################################
# cmake/nuttx_add_prebuilt.cmake
#
# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements.  See the NOTICE file distributed with this work for
# additional information regarding copyright ownership.  The ASF licenses this
# file to you under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.
#
# ##############################################################################

add_custom_target(prebuilt
                  COMMENT "Copy the prebuilt static library for current build")

include(nuttx_parse_function_args)

# ~~~
# nuttx_add_prebuilt
#
# Description:
#    Declare exported prebuilt libraries and export files
#    When in source code repository, create a manifest for prebuilt.
#    When in non-source code repository, use it to add
#    the static library generated by the calling module as extra lib.
#
#    The method sets the `SKIP_PREBUILT` value to `TRUE`
#    when in non-source code repository.
#    The caller needs to stop subsequent builds based on this variable.
#
# Example:
#  nuttx_add_prebuilt(
#    BIN_TARGETS
#    libfoo
#    APP_TARGETS
#    progname
#    EXPORT_FILES
#    include)
#
# ~~~

function(nuttx_add_prebuilt)

  # parse arguments into variables

  nuttx_parse_function_args(
    FUNC
    nuttx_add_prebuilt
    MULTI_VALUE
    BIN_TARGETS
    APP_TARGETS
    EXPORT_FILES
    GLOB_REGEX
    ARGN
    ${ARGN})

  # First, determine whether we are in the source code repo
  if(NOT GLOB_REGEX)
    set(GLOB_REGEX
        ${CMAKE_CURRENT_LIST_DIR}/*.c ${CMAKE_CURRENT_LIST_DIR}/*.cxx
        ${CMAKE_CURRENT_LIST_DIR}/*.cpp ${CMAKE_CURRENT_LIST_DIR}/*.cc)
  endif()

  file(GLOB_RECURSE SOURCE_FILE ${GLOB_REGEX})

  # Skip subsequent builds in non-source environments
  if(NOT SOURCE_FILE)
    set(SKIP_PREBUILT
        TRUE
        PARENT_SCOPE)
  endif()

  # Collect the library generated under the source code
  if(BIN_TARGETS)
    foreach(bin ${BIN_TARGETS})
      list(APPEND EXPORT_LIBS lib${bin}.a)
    endforeach()
  endif()

  if(APP_TARGETS)
    foreach(bin ${APP_TARGETS})
      list(APPEND EXPORT_LIBS libapps_${bin}.a)
    endforeach()
  endif()

  file(RELATIVE_PATH CURRENT_RELATIVE_PATH ${NUTTX_DIR}/..
       ${CMAKE_CURRENT_LIST_DIR})

  # add prebuilt run target
  if(EXPORT_LIBS)
    foreach(lib ${EXPORT_LIBS})
      string(REGEX REPLACE "[^a-zA-Z0-9]" "_" prebuilt_target "${lib}")
      add_custom_target(
        ${prebuilt_target}
        COMMAND
          bash -c
          "find ${CMAKE_BINARY_DIR} -name ${lib} -exec cp -f {} ${PREBUILT_LIB_PATH} \;"
        COMMENT "copying ${lib} to prebuilt path:${PREBUILT_LIB_PATH}"
        VERBATIM)
      add_dependencies(prebuilt ${prebuilt_target})
    endforeach()
  endif()

  # Adding external libraries in a non-source environment
  if(NOT SOURCE_FILE)

    foreach(item IN LISTS EXPORT_LIBS)
      list(APPEND PREBUILT_LIST "${PREBUILT_LIB_PATH}/${item}")
    endforeach()

    file(GLOB EXTRA_LIBS ${PREBUILT_LIST})

    nuttx_add_extra_library(${EXTRA_LIBS})
  endif()

  # FIXME: remove below yaml when prebuilt tool changed
  set(PREBUILT_MANIFEST ${CMAKE_BINARY_DIR}/prebuilt_manifest.yaml)

  if(EXISTS ${PREBUILT_MANIFEST})
    file(READ ${PREBUILT_MANIFEST} file_content)
  else()
    set(file_content "")
  endif()

  if(file_content MATCHES "${CURRENT_RELATIVE_PATH}:")
    return()
  endif()

  string(REPLACE ";" ", " libs_str "${EXPORT_LIBS}")
  string(REPLACE ";" ", " files_str "${EXPORT_FILES}")

  set(yaml_content
      "${CURRENT_RELATIVE_PATH}:\n  EXPORT_LIBS: [${libs_str}]\n  EXPORT_FILES: [${files_str}]\n"
  )

  file(APPEND "${PREBUILT_MANIFEST}" "${yaml_content}")

endfunction()
