/****************************************************************************
 * apps/testing/crypto/psa-arch-tests/include/test_entry_fn_declare_list.inc
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 ****************************************************************************/

#ifdef CONFIG_PSA_ARCH_CRYPTO_TESTS
void test_entry_c001(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c002(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c003(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c004(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c005(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c006(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c007(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c008(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c009(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c010(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c011(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c012(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c013(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c014(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c015(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c016(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c017(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c018(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c019(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c020(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c021(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c022(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c023(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c024(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c025(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c026(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c027(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c028(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c029(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c030(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c031(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c032(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c033(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c034(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c035(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c036(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c037(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c038(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c039(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c040(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c041(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c042(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c043(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c044(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c045(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c046(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c047(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c048(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c049(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c050(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c051(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c052(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c053(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c054(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c055(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c056(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c057(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c058(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c059(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c060(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c061(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c062(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c063(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c064(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c065(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c066(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c067(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c068(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c069(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c070(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c071(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c072(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c073(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c074(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c075(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c076(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c077(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c078(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c079(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_c080(val_api_t *val_api, psa_api_t *psa_api);
#endif
#ifdef CONFIG_PSA_ARCH_ITS_TESTS
void test_entry_s001(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s002(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s003(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s004(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s005(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s006(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s007(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s008(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s009(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s010(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s011(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s012(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s013(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s014(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s015(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s015(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s016(val_api_t *val_api, psa_api_t *psa_api);
void test_entry_s017(val_api_t *val_api, psa_api_t *psa_api);
#endif
#ifdef CONFIG_PSA_ARCH_ATTESTATION_TESTS
void test_entry_a001(val_api_t *val_api, psa_api_t *psa_api);
#endif
